#include "sys_inc.h"
#include "audio_service.h"
#include "bt_audio_service.h"
#include "tone_play_manager.h"
#include "user_config.h"

#define TONE_VOL_MAP_SIZE        3

//提示音音量映射曲线
const vol_map_t tone_vol_map_list[TONE_VOL_MAP_SIZE] = {
    {100, 0 + AUDIO_MUSIC_MAX_VOLUME_DECIBELS},
    {50, -29 + AUDIO_MUSIC_MAX_VOLUME_DECIBELS},
    {0, -73 + AUDIO_MUSIC_MAX_VOLUME_DECIBELS},
};

const sys_tone_info_t sys_tone_info[] = {
#if TONE_WELCOME_EN && defined(TONE_WELCOME_VOL)
    {SYS_TONE_TYPE_WELCOME, SYS_TONE_WELCOME_NAME, TONE_WELCOME_VOL},
#endif

#if TONE_BLUETOOTH_MODE_EN && defined(TONE_BLUETOOTH_MODE_VOL)
    {SYS_TONE_TYPE_BTMODE, SYS_TONE_BTMODE_NAME, TONE_BLUETOOTH_MODE_VOL},
#endif

#if TONE_CONNECTED_EN && defined(TONE_CONNECTED_VOL)
    {SYS_TONE_TYPE_CONNECTED, SYS_TONE_CONNECTED_NAME, TONE_CONNECTED_VOL},
#endif

#if TONE_DISCONNECTED_EN && defined(TONE_DISCONNECTED_VOL)
    {SYS_TONE_TYPE_DISCONNECTED, SYS_TONE_DISCONNECTED_NAME, TONE_DISCONNECTED_VOL},
#endif

#if TONE_PEER_CONNECTED_EN && defined(TONE_PEER_CONNECTED_VOL)
    {SYS_TONE_TYPE_PEER_CONNECTED, SYS_TONE_PEER_CONNECTED_NAME, TONE_PEER_CONNECTED_VOL},
#endif

#if TONE_PEER_DISCONNECTED_EN && defined(TONE_PEER_DISCONNECTED_VOL)
    {SYS_TONE_TYPE_PEER_DISCONNECTED, SYS_TONE_PEER_DISCONNECTED_NAME, TONE_PEER_DISCONNECTED_VOL},
#endif

#if TONE_POWER_OFF_EN && defined(TONE_POWER_OFF_VOL)
    {SYS_TONE_TYPE_POWER_OFF, SYS_TONE_POWER_OFF_NAME, TONE_POWER_OFF_VOL},
#endif

#if TONE_CALL_EN && defined(TONE_CALL_VOL)
    {SYS_TONE_TYPE_CALL, SYS_TONE_CALL_NAME, TONE_CALL_VOL},
#endif

#if TONE_LOW_POWER_EN && defined(TONE_LOW_POWER_VOL)
    {SYS_TONE_TYPE_LOW_POWER, SYS_TONE_LOW_POWER_NAME, TONE_LOW_POWER_VOL},
#endif

#if TONE_GAME_MODE_OPEN_EN && defined(TONE_GAME_MODE_OPEN_VOL)
    {SYS_TONE_TYPE_GAME_MODE_OPEN, SYS_TONE_GAME_MODE_OPEN_NAME, TONE_GAME_MODE_OPEN_VOL},
#endif

#if TONE_GAME_MODE_OPEN_AFX_EN && defined(TONE_GAME_MODE_OPEN_AFX_VOL)
    {SYS_TONE_TYPE_GAME_MODE_OPEN_AFX, SYS_TONE_GAME_MODE_OPEN_AFX_NAME, TONE_GAME_MODE_OPEN_AFX_VOL},
#endif

#if TONE_GAME_MODE_CLOSE_EN && defined(TONE_GAME_MODE_CLOSE_VOL)
    {SYS_TONE_TYPE_GAME_MODE_CLOSE, SYS_TONE_GAME_MODE_CLOSE_NAME, TONE_GAME_MODE_CLOSE_VOL},
#endif

#if TONE_VERSION_ERROR_EN && defined(TONE_VERSION_ERROR_VOL)
    {SYS_TONE_TYPE_VERSION_ERROR, SYS_TONE_VERSION_ERROR_NAME, TONE_VERSION_ERROR_VOL},
#endif

#if TONE_MAX_VOLUME_EN && defined(TONE_VOL_MAX_VOL)
        {SYS_TONE_TYPE_VOL_MAX, SYS_TONE_VOL_MAX_NAME, TONE_VOL_MAX_VOL},
#endif
#if TONE_MIN_VOLUME_EN && defined(TONE_VOL_MIN_VOL)
        {SYS_TONE_TYPE_VOL_MIN, SYS_TONE_VOL_MIN_NAME, TONE_VOL_MIN_VOL},
#endif

#if TONE_EQCONFIG0_EN && defined(TONE_EQCONFIG0_VOL)
        {SYS_TONE_TYPE_EQCONFIG0, SYS_TONE_EQCONFIG0_NAME, TONE_EQCONFIG0_VOL},
#endif

#if TONE_EQCONFIG1_EN && defined(TONE_EQCONFIG1_VOL)
        {SYS_TONE_TYPE_EQCONFIG1, SYS_TONE_EQCONFIG1_NAME, TONE_EQCONFIG1_VOL},
#endif

#if TONE_EQCONFIG2_EN && defined(TONE_EQCONFIG2_VOL)
        {SYS_TONE_TYPE_EQCONFIG2, SYS_TONE_EQCONFIG2_NAME, TONE_EQCONFIG2_VOL},
#endif

#if TONE_EQCONFIG3_EN && defined(TONE_EQCONFIG3_VOL)
        {SYS_TONE_TYPE_EQCONFIG3, SYS_TONE_EQCONFIG3_NAME, TONE_EQCONFIG3_VOL},
#endif
};

void app_audio_tone_config(void)
{
    tone_manager_init_params_t params;

    params.vol_map = tone_vol_map_list;
    params.vol_map_size = TONE_VOL_MAP_SIZE;
    params.sys_tone_info = sys_tone_info;
    params.sys_tone_info_size = sizeof(sys_tone_info) / sizeof(sys_tone_info[0]);
    params.incoming_ringtone_policy = TONE_CALL_EN;
    params.s_con_tone_policy = TONE_M_CONNECTED_NOTIFY_S_PLAY_CONNECTED_TONE;

    am_tone_init(&params);
}
